Add options:
-n [INT]: Set the number of times we will be blinking
-i [INT]: Set the interval between two blinks (in milliseconds)
-v: Verbose output

diff --git a/thinkblink b/thinkblink
--- a/thinkblink
+++ b/thinkblink
@@ -1,19 +1,74 @@
 #!/bin/sh
 
+DEVICE_PATH=/sys/devices/platform/thinkpad_acpi/leds/tpacpi\:\:power
+DEVICE=${DEVICE_PATH}/brightness
 ITERATIONS=10
-INTERVAL=.3
+INTERVAL=.25
 
-cd /sys/devices/platform/thinkpad_acpi/leds/tpacpi\:\:power
+blink() {
+    for ((i=1; i<="$ITERATIONS"; i++))
+    do
+        [[ -n "$VERBOSE" ]] && echo "ON $i / $ITERATIONS"
+        echo "0" > $DEVICE
+        [[ -n "$VERBOSE" ]] && echo "sleep $INTERVAL"
+        sleep $INTERVAL
+        [[ -n "$VERBOSE" ]] && echo "OFF $i / $ITERATIONS"
+        echo "1" > $DEVICE
+        [[ -n "$VERBOSE" ]] && echo "sleep $INTERVAL"
+        sleep $INTERVAL
+    done
+}
 
-SAVED_STATE=$(cat brightness)
+log() {
+    logger "$(basename $0) - Blinked $ITERATIONS times (interval: $INTERVAL)"
+}
 
-for ((i=1; i<=$ITERATIONS; i++))
-do
-    echo "0" > brightness
-    sleep $INTERVAL
-    echo "1" > brightness
-    sleep $INTERVAL
+save_state() {
+    SAVED_STATE=$(cat $DEVICE)
+}
+
+restore_state() {
+    echo "$SAVED_STATE" > $DEVICE
+}
+
+[[ $EUID -ne 0 ]] && {
+   echo "This script must be run as root" 1>&2
+   exit 1
+}
+
+while getopts ":n:i:v" opt; do
+    case $opt in
+        n)
+            [[ "$OPTARG" -eq "$OPTARG" && "$OPTARG" -gt 0 ]] && {
+                ITERATIONS="$OPTARG"
+            }
+            ;;
+        i)
+            [[ "$OPTARG" -eq "$OPTARG" && "$OPTARG" -gt 0 ]] && {
+                INTERVAL="$OPTARG"
+                [[ "$INTERVAL" -gt 1000 ]] && {
+                    let INTERVAL=INTERVAL/1000
+                } || {
+                    INTERVAL=".${INTERVAL}"
+                }
+            }
+            ;;
+        v)
+            VERBOSE=1
+            ;;
+        \?)
+            echo "Invalid option: -$OPTARG" >&2
+            ;;
+        :)
+            echo "Option -$OPTARG requires an argument." >&2
+            exit 1
+            ;;
+    esac
 done
 
-echo "$SAVED_STATE" > brightness
 
+cd "$DEVICE_PATH"
+save_state
+[[ -n $VERBOSE ]] && log
+blink
+restore_state
